### PR TITLE
docs: update github_token input in README

### PR DESCRIPTION
**Pull request by jclarkcisco**
Update `github-token` to `github_token`

### CODE REVIEW

**Review by michael-siek — APPROVED** [review]
@jclarkcisco thank you for your contribution!

**Comment by michael-siek** [comment]
- [x] reviewed for security

**Comment by stephenmathieson** [comment]
This is a breaking change. If merged, we need to create a `v2` branch/update docs/etc.

**Comment by jclarkcisco** [comment]
> * [x]  reviewed for security

👊

**Comment by jclarkcisco** [comment]
@michael-siek - It looks like CLAassistant needs your attention.

**Review by michael-siek — APPROVED** [review]

**Pull request merged**
